### ISSUE TITLE
Waveshare UPS - I'm getting OSError: [Errno 121] Remote I/O error

### ISSUE THREAD

**Issue by teospl** [gloglas/rpi_gui#1]
Hello, 

at first I want to say the project looks very nice and huge thank you for your work! 
I was able to run it without UPS options, but I've just got a UPS and when I try to run the original main.py I get:

Hi! Display routine has started!
Traceback (most recent call last):
  File "/root/rpi_gui/main.py", line 1172, in <module>
    PowerOnReset(bus)
  File "/root/rpi_gui/main.py", line 179, in PowerOnReset
    bus.write_word_data(address, 0xfe, 0x0054)
OSError: [Errno 121] Remote I/O error

I have a Waveshare UPS HAT For Raspberry Pi Zero
do you have any idea how can I deal with it? It's probably about the communication ports differencies but how can I find the mapping for my ups?

**Comment by gloglas** [comment]
Hi, thanks❤ and that's great news!

Waveshare HAT operates bit differently than UPS Lite (Different commands & address). You can take a look on wiki https://www.waveshare.com/wiki/UPS_HAT_(C) , download example code and modify the existing UPS functions with it.
I am planning on making some sort of plugin system but not anytime soon.
